### ISSUE TITLE
Music generation time

### ISSUE THREAD

**Issue by TLNTrung** [AMAAI-Lab/mustango#10]
Can I ask about the time it took for the model to generate a track on your original setup and inquire about possible ways to reduce that time (preferably to around 10 seconds)?
Thanks!

**Comment by guozixunnicolas** [comment]
Hi, thank you for your question. Please refer to _Section 4.3:Inference Settings and Time_ in the updated post-print: https://arxiv.org/pdf/2311.08355 .
