### ISSUE TITLE
method of create MusicBench dataset

### ISSUE THREAD

**Issue by kily-wmz** [AMAAI-Lab/mustango#15]
hi !
Your work is truly amazing! I think your method of augmenting the dataset is great, but I couldn't find the code related to dataset augmentation in the repository. Could you please share the code for this part?

**Comment by dorienh** [comment]
I believe the code should be there, @Dapwner can you check.

**Comment by Dapwner** [comment]
Hiii, thank you for the praise! The augmentation script is in utils/augment_data.py. There are more scripts around in that folder! Have fun exploring. :-)
