### ISSUE TITLE
when and how should i download the audioldm/audioldm-s-full.ckpt

### ISSUE THREAD

**Issue by fundwotsai2001** [AMAAI-Lab/mustango#6]
![Screenshot from 2023-11-21 01-26-39](https://github.com/AMAAI-Lab/mustango/assets/64879498/960a9fa4-b87b-497c-a945-1d43868f37f2)
when and how should i download the audioldm/audioldm-s-full.ckpt, thanks in advance!

**Comment by deepanwayx** [comment]
I have made some changes to `models.py` to download and save it in the cache directory automatically.  

You can also download it from here: https://zenodo.org/record/7600541/files/audioldm-s-full?download=1

and keep it in that cache directory with the `.ckpt` extension.
