### ISSUE TITLE
Can't run after finish installation in Google Colab

### ISSUE THREAD

**Issue by TLNTrung** [AMAAI-Lab/mustango#8]
After I had finished the installation process, when I ran the command 'from mustango import Mustango', it showed an error:

![Screenshot 2023-11-23 103904](https://github.com/AMAAI-Lab/mustango/assets/150533482/219b1434-6ac0-4c2f-96be-fe378664d67e)

Is there an additional step I need to take for it to run on Colab, or have I missed a step?

Thanks!

**Comment by deepanwayx** [comment]
We have prepared a [colab demo notebook](https://colab.research.google.com/drive/1FkbgQgdoEziAluOpayCmTrXULySCBHQa?usp=sharing).

Please make your own copy to use it. However, you will need a colab pro account to run this, as the free one goes out of memory during execution.
