### ISSUE TITLE
Possible pipeline

### ISSUE THREAD

**Issue by TLNTrung** [AMAAI-Lab/mustango#9]
I would like to request a pipeline for our project in the near future if possible. 
Thank you for the amazing work so far.

**Comment by dorienh** [comment]
Can you elaborate on the pipeline you would need? Do you want to run locally or remote via API?

**Comment by TLNTrung** [comment]
I would prefer both, but I prioritize the local option.

**Comment by dorienh** [comment]
You can use Mustango hosted on Replicate which offers API: https://replicate.com/declare-lab/mustango

Locally, you can run the `predict.py` script as specified in the readme, a pip install pipeline is being developed by @deepanwayx

**Comment by TLNTrung** [comment]
Okay, thanks
